export { ProductsTab } from './ProductsTab'
export { RentalsTab } from './RentalsTab'
export { SalesTab } from './SalesTab'
export { SuppliersTab } from './SuppliersTab'
export { CustomersTab } from './CustomersTab'
export { CustomerFormModal } from './CustomerFormModal'
export { InventoryView } from './InventoryView'
